/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class Client {
  /**
   * Constructor required by napi-rs class registry.  Always throws —
   * use `new Client(options)`.
   */
  constructor(options?: any | undefined | null)
  /**
   * Read affinity key pinning reads to a stable replica
   * (`X-Qdrant-Route-Affinity`, Qdrant 1.19+). Set via
   * `new Client({ routeAffinity })`.
   */
  get routeAffinity(): string | null
  /**
   * Execute a QQL query string, a Stmt, or an array of either.
   * Multi-statement strings (semicolons) and arrays are auto-batched.
   * Returns a stable ExecutionReport JSON string for the JavaScript wrapper
   * to deserialize into an object.
   */
  execute(query: string | Stmt | string[] | Stmt[], options?: { onError?: 'stop' | 'continue', params?: Record<string, any> | any[] }): Promise<string>
  explain(query: string): string
  explainStmt(stmt: Stmt): string
  /** Compile a QQL query to its transport route (non-executing). */
  compile(query: string, params: unknown): any
  /**
   * Bulk ingest: `rows` is an array of point objects
   * (`{id, vector, …payload}`) spliced through the `:rows` point-splice
   * path in `batchSize` chunks (default 100). Vectors accept plain arrays
   * and the flat `{data, dim}` multivector form. Like [`JsClient::execute`]
   * this is a serde boundary: `Float32Array`/`Float64Array` do not survive
   * it — bind those on the sync `Stmt.bind` surface instead, then execute
   * the bound statement. Returns a stable ExecutionReport JSON string.
   */
  upsertMany(collection: string, rows: Record<string, any>[], options?: { onError?: 'stop' | 'continue', batchSize?: number }): Promise<string>
  /** Close the client and release underlying connections. */
  close(): Promise<void>
}
export type JsClient = Client

export declare class Stmt {
  /**
   * Parse a QQL string into a Stmt handle (mirrors `qql-wasm`'s
   * `new Stmt(query)` — see the filter-injection guide).
   */
  constructor(input: string)
  injectFilter(field: string, op: string, value: any): void
  toObject(): any
  toJson(): string
  /**
   * QQL `SHARD` routing key (request-level). Prefer the clause in QQL.
   *
   * Reads back `string` for keyword keys, `bigint` for numeric keys, and
   * `null` when unset (placeholders also read as `null` — bind first).
   * The setter accepts `string | number | bigint | null`: numbers must be
   * exact non-negative integers (larger keys need `BigInt`).
   */
  get shardKey(): string | bigint | null
  set shardKeystring | number | bigint | null | undefined
  /** Whether parameters have already been bound into this statement. */
  get bound(): boolean
  /**
   * Bind parameters into this statement and return a new bound Stmt.
   * Vector params accept plain arrays as well as `Float32Array` /
   * `Float64Array` (one memcpy, no per-element walk).
   */
  bind(params: unknown): Stmt
  /** Format statement as canonical, re-parseable QQL (mirrors Python `str(stmt)`). */
  toString(): string
  /**
   * Format statement as a human-readable preview (mirrors Python `repr(stmt)`):
   * long vector literals are truncated, so the output may not re-parse.
   */
  toReadableString(): string
  /**
   * Compile this Stmt AST directly into its transport route without re-parsing.
   * Optionally accepts `params` to bind before compiling.
   */
  compileRoute(params: unknown): any
}

/**
 * Substitute `:name` (object) or `?` (array) placeholders into a query string.
 * Without `params`, the query is returned unchanged. With `truncateVectors`,
 * long vector literals render as `[0.1, 0.2, ... (N dims)]` for previews.
 * (Stmt inputs are handled by the JS wrapper, which routes to `Stmt.bind`.)
 */
export declare function bind(query: string, params?: Record<string, any> | any[], options?: { truncateVectors?: boolean }): string

export declare function compileQuery(input: string, params: unknown): any

export declare function execute(query: string | Stmt | string[] | Stmt[], options?: { onError?: 'stop' | 'continue', params?: Record<string, any> | any[] }): Promise<string>

/** Execute a pre-parsed Stmt directly via a new temporary client. */
export declare function executeStmt(stmt: Stmt, options?: object): Promise<string>

export declare function explain(query: string): string

export declare function explainStmt(stmt: Stmt): string

export declare function injectFilter(query: string, field: string, op: string, value: any): any

export declare function isValid(input: string): boolean

export declare function parseAll(input: string): Array<Stmt>

/**
 * Fast JSON-only parse — returns a JSON string of the AST array.
 * Bypasses V8 Stmt object allocation entirely (~2× throughput).
 * Ideal for HTTP/IPC forwarding.
 */
export declare function parseAllJson(input: string): string

export declare function tokenize(input: string): any
