/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const __wbg_client_free: (a: number, b: number) => void;
export const __wbg_stmt_free: (a: number, b: number) => void;
export const analyze: (a: number, b: number) => [number, number, number];
export const client_compile: (a: number, b: number, c: number) => [number, number, number];
export const client_execute: (a: number, b: any, c: number) => any;
export const client_executeStmt: (a: number, b: number) => any;
export const client_explain: (a: number, b: number, c: number) => [number, number, number, number];
export const client_hasEmbedder: (a: number) => number;
export const client_new: (a: number, b: number, c: number, d: number) => number;
export const client_setEmbedder: (a: number, b: any) => void;
export const client_setHttpEmbedder: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number) => [number, number];
export const client_setRemoteEmbedder: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number) => [number, number];
export const compile: (a: number, b: number) => [number, number, number];
export const compileBytes: (a: number, b: number) => [number, number, number];
export const explain: (a: number, b: number) => [number, number, number, number];
export const explainBytes: (a: number, b: number) => [number, number, number];
export const injectShardKey: (a: number, b: number, c: number, d: number) => [number, number, number];
export const inject_filter: (a: number, b: number, c: number, d: number, e: number, f: number, g: any) => [number, number, number];
export const isValid: (a: number, b: number) => number;
export const parse: (a: number, b: number) => [number, number, number];
export const stmt_compileRoute: (a: number) => [number, number, number];
export const stmt_compileRouteBytes: (a: number) => [number, number, number];
export const stmt_injectFilter: (a: number, b: number, c: number, d: number, e: number, f: any) => [number, number];
export const stmt_injectShardKey: (a: number, b: number, c: number) => [number, number];
export const stmt_new: (a: number, b: number) => [number, number, number];
export const stmt_set_shardKey: (a: number, b: number, c: number) => void;
export const stmt_shardKey: (a: number) => [number, number];
export const stmt_toJSON: (a: number) => [number, number, number, number];
export const stmt_toObject: (a: number) => [number, number, number];
export const tokenize: (a: number, b: number) => [number, number, number, number];
export const wasm_bindgen__convert__closures_____invoke__h7b246c2cec5ed1a2: (a: number, b: number, c: any) => [number, number];
export const wasm_bindgen__convert__closures_____invoke__he337ed6031f9a7b2: (a: number, b: number, c: any, d: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h9ca81c2f6cf976b5: (a: number, b: number) => number;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_exn_store: (a: number) => void;
export const __externref_table_alloc: () => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __wbindgen_destroy_closure: (a: number, b: number) => void;
export const __externref_table_dealloc: (a: number) => void;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __externref_drop_slice: (a: number, b: number) => void;
export const __wbindgen_start: () => void;
