from typing import Any, Dict, List, Optional, Union

__version__: str

class Stmt:
    def __init__(self, input: str) -> None: ...
    @property
    def shard_key(self) -> Optional[str]: ...
    @shard_key.setter
    def shard_key(self, value: Optional[str]) -> None: ...
    def inject_filter(self, field: str, op: str, value: Any) -> None: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...

class HttpEmbedder:
    def __init__(
        self,
        endpoint: str,
        api_key: Optional[str] = None,
        model: Optional[str] = None,
        dimension: Optional[int] = None,
    ) -> None: ...

class Client:
    def __init__(
        self,
        url: str = "http://localhost:6333",
        api_key: Optional[str] = None,
        embedder: Optional[HttpEmbedder] = None,
    ) -> None: ...
    def execute(self, query: str, on_error: str = "stop") -> Dict[str, Any]: ...
    def execute_async(self, query: str, on_error: str = "stop") -> Dict[str, Any]: ...
    def close(self) -> None: ...

def parse(input: str) -> List[Stmt]: ...
def is_valid(input: str) -> bool: ...
def explain(query: str) -> str: ...
def compile_query(query: str) -> Dict[str, Any]: ...
def tokenize(input: str) -> List[Dict[str, Any]]: ...
def inject_filter(query: str, field: str, op: str, value: Any) -> Dict[str, Any]: ...
def execute(query: str, url: str = "http://localhost:6333", api_key: Optional[str] = None) -> Dict[str, Any]: ...
def execute_async(query: str, url: str = "http://localhost:6333", api_key: Optional[str] = None) -> Dict[str, Any]: ...
