from typing import Any, Dict, List, Optional, Union

__version__: str

class Stmt:
    def __init__(self, input: str) -> None: ...
    @property
    def shard_key(self) -> Optional[str]: ...
    @shard_key.setter
    def shard_key(self, value: Optional[str]) -> None: ...
    def inject_filter(self, field: str, op: str, value: Any) -> None: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self) -> str: ...

class Client:
    def __init__(
        self,
        data_dir: Optional[str] = None,
        embedder: str = "fastembed",
        model: Optional[str] = None,
        embed_url: Optional[str] = None,
        embed_key: Optional[str] = None,
        embed_model: Optional[str] = None,
        embed_dim: Optional[int] = None,
    ) -> None: ...
    def execute(self, query: str) -> Dict[str, Any]: ...
    def execute_async(self, query: str) -> Dict[str, Any]: ...
    def close(self) -> None: ...

def parse(input: str) -> List[Stmt]: ...
def is_valid(input: str) -> bool: ...
def explain(query: str) -> str: ...
def compile_query(query: str) -> Dict[str, Any]: ...
def tokenize(input: str) -> List[Dict[str, Any]]: ...
def inject_filter(query: str, field: str, op: str, value: Any) -> Dict[str, Any]: ...
def parse_json(input: str) -> Dict[str, Any]: ...
def local_executor(data_dir: Optional[str] = None, model: Optional[str] = None) -> Any: ...
def http_executor(data_dir: Optional[str] = None, embed_url: str = ...) -> Any: ...
def list_embedding_models() -> List[str]: ...
def execute(query: str, data_dir: Optional[str] = None) -> Dict[str, Any]: ...
def execute_async(query: str, data_dir: Optional[str] = None) -> Dict[str, Any]: ...
