use core::fmt;

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum TokenKind {
    Insert,
    Into,
    Collection,
    Values,
    Using,
    Model,
    Hybrid,
    Dense,
    Sparse,
    Rerank,
    Exact,
    With,
    As,
    Acorn,
    Quantize,
    Scalar,
    Binary,
    Product,
    Turbo,
    Bits,
    Quantile,
    Always,
    Ram,
    Hnsw,
    Vectors,
    Optimizers,
    Params,
    Disabled,
    Create,
    Alter,
    Drop,
    Show,
    Collections,
    Select,
    Scroll,
    Star,
    After,
    Recommend,
    Limit,
    Group,
    By,
    GroupSize,
    Strategy,
    Delete,
    Update,
    Set,
    Vector,
    Payload,
    From,
    Where,
    Id,
    Index,
    On,
    For,
    Type,
    And,
    Or,
    Not,
    In,
    Between,
    Is,
    Null,
    Empty,
    Match,
    Any,
    Phrase,
    Offset,
    Score,
    Threshold,
    Lookup,
    Cosine,
    Dot,
    Euclid,
    Manhattan,
    Order,
    Asc,
    Desc,
    Query,
    Nearest,
    Context,
    Discover,
    Pairs,
    Target,
    Identifier,
    String,
    Integer,
    Float,
    Lbrace,
    Rbrace,
    Lbracket,
    Rbracket,
    Lparen,
    Rparen,
    Colon,
    Comma,
    Equals,
    NotEquals,
    Gt,
    Gte,
    Lt,
    Lte,
    GeoBbox,
    GeoRadius,
    ValuesCount,
    HasVector,
    Prefetch,
    Fusion,
    Sample,
    Boost,
    Defaults,
    Case,
    When,
    Then,
    Else,
    End,
    Plus,
    Minus,
    Slash,
    Relevance,
    Feedback,
    Eof,
}

impl TokenKind {
    pub fn as_str(&self) -> &'static str {
        match self {
            TokenKind::Insert => "INSERT",
            TokenKind::Into => "INTO",
            TokenKind::Collection => "COLLECTION",
            TokenKind::Values => "VALUES",
            TokenKind::Using => "USING",
            TokenKind::Model => "MODEL",
            TokenKind::Hybrid => "HYBRID",
            TokenKind::Dense => "DENSE",
            TokenKind::Sparse => "SPARSE",
            TokenKind::Rerank => "RERANK",
            TokenKind::Exact => "EXACT",
            TokenKind::With => "WITH",
            TokenKind::As => "AS",
            TokenKind::Acorn => "ACORN",
            TokenKind::Quantize => "QUANTIZE",
            TokenKind::Scalar => "SCALAR",
            TokenKind::Binary => "BINARY",
            TokenKind::Product => "PRODUCT",
            TokenKind::Turbo => "TURBO",
            TokenKind::Bits => "BITS",
            TokenKind::Quantile => "QUANTILE",
            TokenKind::Always => "ALWAYS",
            TokenKind::Ram => "RAM",
            TokenKind::Hnsw => "HNSW",
            TokenKind::Vectors => "VECTORS",
            TokenKind::Optimizers => "OPTIMIZERS",
            TokenKind::Params => "PARAMS",
            TokenKind::Disabled => "DISABLED",
            TokenKind::Create => "CREATE",
            TokenKind::Alter => "ALTER",
            TokenKind::Drop => "DROP",
            TokenKind::Show => "SHOW",
            TokenKind::Collections => "COLLECTIONS",
            TokenKind::Select => "SELECT",
            TokenKind::Scroll => "SCROLL",
            TokenKind::Star => "STAR",
            TokenKind::After => "AFTER",
            TokenKind::Recommend => "RECOMMEND",
            TokenKind::Limit => "LIMIT",
            TokenKind::Group => "GROUP",
            TokenKind::By => "BY",
            TokenKind::GroupSize => "GROUP_SIZE",
            TokenKind::Strategy => "STRATEGY",
            TokenKind::Delete => "DELETE",
            TokenKind::Update => "UPDATE",
            TokenKind::Set => "SET",
            TokenKind::Vector => "VECTOR",
            TokenKind::Payload => "PAYLOAD",
            TokenKind::From => "FROM",
            TokenKind::Where => "WHERE",
            TokenKind::Id => "ID",
            TokenKind::Index => "INDEX",
            TokenKind::On => "ON",
            TokenKind::For => "FOR",
            TokenKind::Type => "TYPE",
            TokenKind::And => "AND",
            TokenKind::Or => "OR",
            TokenKind::Not => "NOT",
            TokenKind::In => "IN",
            TokenKind::Between => "BETWEEN",
            TokenKind::Is => "IS",
            TokenKind::Null => "NULL",
            TokenKind::Empty => "EMPTY",
            TokenKind::Match => "MATCH",
            TokenKind::Any => "ANY",
            TokenKind::Phrase => "PHRASE",
            TokenKind::Offset => "OFFSET",
            TokenKind::Score => "SCORE",
            TokenKind::Threshold => "THRESHOLD",
            TokenKind::Lookup => "LOOKUP",
            TokenKind::Cosine => "COSINE",
            TokenKind::Dot => "DOT",
            TokenKind::Euclid => "EUCLID",
            TokenKind::Manhattan => "MANHATTAN",
            TokenKind::Order => "ORDER",
            TokenKind::Asc => "ASC",
            TokenKind::Desc => "DESC",
            TokenKind::Query => "QUERY",
            TokenKind::Nearest => "NEAREST",
            TokenKind::Context => "CONTEXT",
            TokenKind::Discover => "DISCOVER",
            TokenKind::Pairs => "PAIRS",
            TokenKind::Target => "TARGET",
            TokenKind::Identifier => "IDENTIFIER",
            TokenKind::String => "STRING",
            TokenKind::Integer => "INTEGER",
            TokenKind::Float => "FLOAT",
            TokenKind::Lbrace => "LBRACE",
            TokenKind::Rbrace => "RBRACE",
            TokenKind::Lbracket => "LBRACKET",
            TokenKind::Rbracket => "RBRACKET",
            TokenKind::Lparen => "LPAREN",
            TokenKind::Rparen => "RPAREN",
            TokenKind::Colon => "COLON",
            TokenKind::Comma => "COMMA",
            TokenKind::Equals => "EQUALS",
            TokenKind::NotEquals => "NOT_EQUALS",
            TokenKind::Gt => "GT",
            TokenKind::Gte => "GTE",
            TokenKind::Lt => "LT",
            TokenKind::Lte => "LTE",
            TokenKind::GeoBbox => "GEO_BBOX",
            TokenKind::GeoRadius => "GEO_RADIUS",
            TokenKind::ValuesCount => "VALUES_COUNT",
            TokenKind::HasVector => "HAS_VECTOR",
            TokenKind::Prefetch => "PREFETCH",
            TokenKind::Fusion => "FUSION",
            TokenKind::Sample => "SAMPLE",
            TokenKind::Boost => "BOOST",
            TokenKind::Defaults => "DEFAULTS",
            TokenKind::Case => "CASE",
            TokenKind::When => "WHEN",
            TokenKind::Then => "THEN",
            TokenKind::Else => "ELSE",
            TokenKind::End => "END",
            TokenKind::Plus => "PLUS",
            TokenKind::Minus => "MINUS",
            TokenKind::Slash => "SLASH",
            TokenKind::Relevance => "RELEVANCE",
            TokenKind::Feedback => "FEEDBACK",
            TokenKind::Eof => "EOF",
        }
    }
}

impl fmt::Display for TokenKind {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str(self.as_str())
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct Token<'a> {
    pub kind: TokenKind,
    pub text: &'a str,
    pub pos: usize,
}

impl<'a> Token<'a> {
    pub fn new(kind: TokenKind, text: &'a str, pos: usize) -> Self {
        Token { kind, text, pos }
    }

    pub fn eof() -> Self {
        Token {
            kind: TokenKind::Eof,
            text: "",
            pos: 0,
        }
    }
}

impl<'a> fmt::Display for Token<'a> {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "{}({})", self.kind, self.text)
    }
}

pub static KEYWORDS: phf::Map<&'static str, TokenKind> = phf::phf_map! {
    "INSERT" => TokenKind::Insert,
    "INTO" => TokenKind::Into,
    "COLLECTION" => TokenKind::Collection,
    "VALUES" => TokenKind::Values,
    "USING" => TokenKind::Using,
    "MODEL" => TokenKind::Model,
    "HYBRID" => TokenKind::Hybrid,
    "DENSE" => TokenKind::Dense,
    "SPARSE" => TokenKind::Sparse,
    "RERANK" => TokenKind::Rerank,
    "EXACT" => TokenKind::Exact,
    "WITH" => TokenKind::With,
    "AS" => TokenKind::As,
    "ACORN" => TokenKind::Acorn,
    "QUANTIZE" => TokenKind::Quantize,
    "SCALAR" => TokenKind::Scalar,
    "BINARY" => TokenKind::Binary,
    "PRODUCT" => TokenKind::Product,
    "TURBO" => TokenKind::Turbo,
    "BITS" => TokenKind::Bits,
    "QUANTILE" => TokenKind::Quantile,
    "ALWAYS" => TokenKind::Always,
    "RAM" => TokenKind::Ram,
    "HNSW" => TokenKind::Hnsw,
    "VECTORS" => TokenKind::Vectors,
    "OPTIMIZERS" => TokenKind::Optimizers,
    "PARAMS" => TokenKind::Params,
    "DISABLED" => TokenKind::Disabled,
    "CREATE" => TokenKind::Create,
    "ALTER" => TokenKind::Alter,
    "DROP" => TokenKind::Drop,
    "SHOW" => TokenKind::Show,
    "COLLECTIONS" => TokenKind::Collections,
    "SELECT" => TokenKind::Select,
    "SCROLL" => TokenKind::Scroll,
    "AFTER" => TokenKind::After,
    "RECOMMEND" => TokenKind::Recommend,
    "LIMIT" => TokenKind::Limit,
    "GROUP" => TokenKind::Group,
    "BY" => TokenKind::By,
    "GROUP_SIZE" => TokenKind::GroupSize,
    "STRATEGY" => TokenKind::Strategy,
    "DELETE" => TokenKind::Delete,
    "UPDATE" => TokenKind::Update,
    "SET" => TokenKind::Set,
    "VECTOR" => TokenKind::Vector,
    "PAYLOAD" => TokenKind::Payload,
    "FROM" => TokenKind::From,
    "WHERE" => TokenKind::Where,
    "ID" => TokenKind::Id,
    "INDEX" => TokenKind::Index,
    "ON" => TokenKind::On,
    "FOR" => TokenKind::For,
    "TYPE" => TokenKind::Type,
    "AND" => TokenKind::And,
    "OR" => TokenKind::Or,
    "NOT" => TokenKind::Not,
    "IN" => TokenKind::In,
    "BETWEEN" => TokenKind::Between,
    "IS" => TokenKind::Is,
    "NULL" => TokenKind::Null,
    "EMPTY" => TokenKind::Empty,
    "MATCH" => TokenKind::Match,
    "ANY" => TokenKind::Any,
    "PHRASE" => TokenKind::Phrase,
    "OFFSET" => TokenKind::Offset,
    "SCORE" => TokenKind::Score,
    "THRESHOLD" => TokenKind::Threshold,
    "LOOKUP" => TokenKind::Lookup,
    "COSINE" => TokenKind::Cosine,
    "DOT" => TokenKind::Dot,
    "EUCLID" => TokenKind::Euclid,
    "MANHATTAN" => TokenKind::Manhattan,
    "ORDER" => TokenKind::Order,
    "ASC" => TokenKind::Asc,
    "DESC" => TokenKind::Desc,
    "QUERY" => TokenKind::Query,
    "NEAREST" => TokenKind::Nearest,
    "CONTEXT" => TokenKind::Context,
    "DISCOVER" => TokenKind::Discover,
    "PAIRS" => TokenKind::Pairs,
    "TARGET" => TokenKind::Target,
    "PREFETCH" => TokenKind::Prefetch,
    "FUSION" => TokenKind::Fusion,
    "SAMPLE" => TokenKind::Sample,
    "BOOST" => TokenKind::Boost,
    "DEFAULTS" => TokenKind::Defaults,
    "CASE" => TokenKind::Case,
    "WHEN" => TokenKind::When,
    "THEN" => TokenKind::Then,
    "ELSE" => TokenKind::Else,
    "END" => TokenKind::End,
    "GEO_BBOX" => TokenKind::GeoBbox,
    "GEO_RADIUS" => TokenKind::GeoRadius,
    "VALUES_COUNT" => TokenKind::ValuesCount,
    "HAS_VECTOR" => TokenKind::HasVector,
    "RELEVANCE" => TokenKind::Relevance,
    "FEEDBACK" => TokenKind::Feedback,
};

pub fn lookup_keyword(s: &str) -> Option<TokenKind> {
    let bytes = s.as_bytes();
    let len = bytes.len();
    if len == 0 || len > 32 {
        return None;
    }
    let mut buf = [0u8; 32];
    for (i, b) in bytes.iter().enumerate() {
        buf[i] = b.to_ascii_uppercase();
    }
    let upper = core::str::from_utf8(&buf[..len]).ok()?;
    KEYWORDS.get(upper).copied()
}
