use core::fmt;

use crate::error::Span;

// ── Token kind definitions ─────────────────────────────────────
// All variants are listed ONCE in the `token_table!`.
// Two helper macros consume that table to produce:
//   • as_str()     – for all variants
//   • KEYWORDS map – for keyword-only variants

macro_rules! gen_as_str {
    ($($var:ident => $str:expr),* $(,)?) => {
        impl TokenKind {
            pub fn as_str(&self) -> &'static str {
                match self {
                    $( Self::$var => $str, )*
                }
            }
        }
    };
}

macro_rules! gen_keywords {
    ($($str:expr => TokenKind::$var:ident),* $(,)?) => {
        pub static KEYWORDS: phf::Map<&'static str, TokenKind> = phf::phf_map! {
            $( $str => TokenKind::$var, )*
        };
    };
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize))]
pub enum TokenKind {
    A,
    Abs,
    Acorn,
    After,
    All,
    Alter,
    And,
    Any,
    As,
    Asc,
    AverageVector,
    B,
    BestScore,
    Between,
    Bool,
    BottomRight,
    By,
    C,
    Candidates,
    Case,
    Center,
    Clear,
    Collection,
    Collections,
    Consistency,
    Context,
    Cosine,
    Count,
    Create,
    Cross,
    Datetime,
    DatetimeKey,
    Dbsf,
    Decay,
    Default,
    Defaults,
    Delete,
    Dense,
    Desc,
    Discover,
    Diversity,
    Dot,
    Drop,
    E,
    Else,
    Embed,
    Empty,
    End,
    Euclid,
    Exact,
    Exclude,
    Exp,
    ExpDecay,
    Exterior,
    False,
    Feedback,
    Field,
    Float,
    For,
    Formula,
    From,
    Fusion,
    GaussDecay,
    Geo,
    GeoBbox,
    GeoDistance,
    GeoPolygon,
    GeoRadius,
    Group,
    HasVector,
    Hnsw,
    HnswEf,
    Hybrid,
    Id,
    Ignore,
    Image,
    In,
    Include,
    Index,
    IndexedOnly,
    Indices,
    Integer,
    Interiors,
    Into,
    Is,
    Key,
    Keys,
    Keyword,
    Lat,
    Limit,
    LinDecay,
    Ln,
    Log,
    Lon,
    Lookup,
    Majority,
    Manhattan,
    Match,
    MatchAny,
    MaxSelectivity,
    Midpoint,
    Mmr,
    Model,
    Multi,
    Multivector,
    Naive,
    Nearest,
    Negative,
    Nested,
    Not,
    Null,
    Offset,
    On,
    Optimizers,
    Or,
    Order,
    Oversampling,
    Params,
    Payload,
    Phrase,
    Point,
    Points,
    Positive,
    Pow,
    Prefetch,
    Quantization,
    Query,
    Quorum,
    Radius,
    Random,
    Recommend,
    Relevance,
    Rerank,
    Rescore,
    Rrf,
    RrfK,
    RrfWeights,
    Sample,
    Scale,
    Score,
    Scroll,
    Set,
    Shard,
    Show,
    Size,
    Sparse,
    Sqrt,
    Strategy,
    SumScores,
    Target,
    Text,
    Then,
    Threshold,
    Timeout,
    TopLeft,
    True,
    Type,
    Update,
    Upsert,
    Using,
    Uuid,
    Values,
    ValuesCount,
    Vector,
    When,
    Where,
    With,
    X,
    Star,
    Identifier,
    String,
    Lbrace,
    Rbrace,
    Lbracket,
    Rbracket,
    Lparen,
    Rparen,
    Colon,
    Comma,
    Equals,
    NotEquals,
    Gt,
    Gte,
    Lt,
    Lte,
    Plus,
    Minus,
    Slash,
    Semicolon,
    Eof,
}

gen_as_str! {
    A => "A",
    Abs => "ABS",
    Acorn => "ACORN",
    After => "AFTER",
    All => "ALL",
    Alter => "ALTER",
    And => "AND",
    Any => "ANY",
    As => "AS",
    Asc => "ASC",
    AverageVector => "AVERAGE_VECTOR",
    B => "B",
    BestScore => "BEST_SCORE",
    Between => "BETWEEN",
    Bool => "BOOL",
    BottomRight => "BOTTOM_RIGHT",
    By => "BY",
    C => "C",
    Candidates => "CANDIDATES",
    Case => "CASE",
    Center => "CENTER",
    Clear => "CLEAR",
    Collection => "COLLECTION",
    Collections => "COLLECTIONS",
    Consistency => "CONSISTENCY",
    Context => "CONTEXT",
    Cosine => "COSINE",
    Count => "COUNT",
    Create => "CREATE",
    Cross => "CROSS",
    Datetime => "DATETIME",
    DatetimeKey => "DATETIME_KEY",
    Dbsf => "DBSF",
    Decay => "DECAY",
    Default => "DEFAULT",
    Defaults => "DEFAULTS",
    Delete => "DELETE",
    Dense => "DENSE",
    Desc => "DESC",
    Discover => "DISCOVER",
    Diversity => "DIVERSITY",
    Dot => "DOT",
    Drop => "DROP",
    E => "E",
    Else => "ELSE",
    Embed => "EMBED",
    Empty => "EMPTY",
    End => "END",
    Euclid => "EUCLID",
    Exact => "EXACT",
    Exclude => "EXCLUDE",
    Exp => "EXP",
    ExpDecay => "EXP_DECAY",
    Exterior => "EXTERIOR",
    False => "FALSE",
    Feedback => "FEEDBACK",
    Field => "FIELD",
    Float => "FLOAT",
    For => "FOR",
    Formula => "FORMULA",
    From => "FROM",
    Fusion => "FUSION",
    GaussDecay => "GAUSS_DECAY",
    Geo => "GEO",
    GeoBbox => "GEO_BBOX",
    GeoDistance => "GEO_DISTANCE",
    GeoPolygon => "GEO_POLYGON",
    GeoRadius => "GEO_RADIUS",
    Group => "GROUP",
    HasVector => "HAS_VECTOR",
    Hnsw => "HNSW",
    HnswEf => "HNSW_EF",
    Hybrid => "HYBRID",
    Id => "ID",
    Ignore => "IGNORE",
    Image => "IMAGE",
    In => "IN",
    Include => "INCLUDE",
    Index => "INDEX",
    IndexedOnly => "INDEXED_ONLY",
    Indices => "INDICES",
    Integer => "INTEGER",
    Interiors => "INTERIORS",
    Into => "INTO",
    Is => "IS",
    Key => "KEY",
    Keys => "KEYS",
    Keyword => "KEYWORD",
    Lat => "LAT",
    Limit => "LIMIT",
    LinDecay => "LIN_DECAY",
    Ln => "LN",
    Log => "LOG",
    Lon => "LON",
    Lookup => "LOOKUP",
    Majority => "MAJORITY",
    Manhattan => "MANHATTAN",
    Match => "MATCH",
    MatchAny => "MATCH_ANY",
    MaxSelectivity => "MAX_SELECTIVITY",
    Midpoint => "MIDPOINT",
    Mmr => "MMR",
    Model => "MODEL",
    Multi => "MULTI",
    Multivector => "MULTIVECTOR",
    Naive => "NAIVE",
    Nearest => "NEAREST",
    Negative => "NEGATIVE",
    Nested => "NESTED",
    Not => "NOT",
    Null => "NULL",
    Offset => "OFFSET",
    On => "ON",
    Optimizers => "OPTIMIZERS",
    Or => "OR",
    Order => "ORDER",
    Oversampling => "OVERSAMPLING",
    Params => "PARAMS",
    Payload => "PAYLOAD",
    Phrase => "PHRASE",
    Point => "POINT",
    Points => "POINTS",
    Positive => "POSITIVE",
    Pow => "POW",
    Prefetch => "PREFETCH",
    Quantization => "QUANTIZATION",
    Query => "QUERY",
    Quorum => "QUORUM",
    Radius => "RADIUS",
    Random => "RANDOM",
    Recommend => "RECOMMEND",
    Relevance => "RELEVANCE",
    Rerank => "RERANK",
    Rescore => "RESCORE",
    Rrf => "RRF",
    RrfK => "RRF_K",
    RrfWeights => "RRF_WEIGHTS",
    Sample => "SAMPLE",
    Scale => "SCALE",
    Score => "SCORE",
    Scroll => "SCROLL",
    Set => "SET",
    Shard => "SHARD",
    Show => "SHOW",
    Size => "SIZE",
    Sparse => "SPARSE",
    Sqrt => "SQRT",
    Strategy => "STRATEGY",
    SumScores => "SUM_SCORES",
    Target => "TARGET",
    Text => "TEXT",
    Then => "THEN",
    Threshold => "THRESHOLD",
    Timeout => "TIMEOUT",
    TopLeft => "TOP_LEFT",
    True => "TRUE",
    Type => "TYPE",
    Update => "UPDATE",
    Upsert => "UPSERT",
    Using => "USING",
    Uuid => "UUID",
    Values => "VALUES",
    ValuesCount => "VALUES_COUNT",
    Vector => "VECTOR",
    When => "WHEN",
    Where => "WHERE",
    With => "WITH",
    X => "X",
    Star => "*",
    Identifier => "IDENTIFIER",
    String => "STRING",
    Lbrace => "LBRACE",
    Rbrace => "RBRACE",
    Lbracket => "LBRACKET",
    Rbracket => "RBRACKET",
    Lparen => "LPAREN",
    Rparen => "RPAREN",
    Colon => "COLON",
    Comma => "COMMA",
    Equals => "EQUALS",
    NotEquals => "NOT_EQUALS",
    Gt => "GT",
    Gte => "GTE",
    Lt => "LT",
    Lte => "LTE",
    Plus => "PLUS",
    Minus => "MINUS",
    Slash => "SLASH",
    Semicolon => "SEMICOLON",
    Eof => "EOF",
}

gen_keywords! {
    "A" => TokenKind::A,
    "ABS" => TokenKind::Abs,
    "ACORN" => TokenKind::Acorn,
    "AFTER" => TokenKind::After,
    "ALL" => TokenKind::All,
    "ALTER" => TokenKind::Alter,
    "AND" => TokenKind::And,
    "ANY" => TokenKind::Any,
    "AS" => TokenKind::As,
    "ASC" => TokenKind::Asc,
    "AVERAGE_VECTOR" => TokenKind::AverageVector,
    "B" => TokenKind::B,
    "BEST_SCORE" => TokenKind::BestScore,
    "BETWEEN" => TokenKind::Between,
    "BOOL" => TokenKind::Bool,
    "BOTTOM_RIGHT" => TokenKind::BottomRight,
    "BY" => TokenKind::By,
    "C" => TokenKind::C,
    "CANDIDATES" => TokenKind::Candidates,
    "CASE" => TokenKind::Case,
    "CENTER" => TokenKind::Center,
    "CLEAR" => TokenKind::Clear,
    "COLLECTION" => TokenKind::Collection,
    "COLLECTIONS" => TokenKind::Collections,
    "CONSISTENCY" => TokenKind::Consistency,
    "CONTEXT" => TokenKind::Context,
    "COSINE" => TokenKind::Cosine,
    "COUNT" => TokenKind::Count,
    "CREATE" => TokenKind::Create,
    "CROSS" => TokenKind::Cross,
    "DATETIME" => TokenKind::Datetime,
    "DATETIME_KEY" => TokenKind::DatetimeKey,
    "DBSF" => TokenKind::Dbsf,
    "DECAY" => TokenKind::Decay,
    "DEFAULT" => TokenKind::Default,
    "DEFAULTS" => TokenKind::Defaults,
    "DELETE" => TokenKind::Delete,
    "DENSE" => TokenKind::Dense,
    "DESC" => TokenKind::Desc,
    "DISCOVER" => TokenKind::Discover,
    "DIVERSITY" => TokenKind::Diversity,
    "DOT" => TokenKind::Dot,
    "DROP" => TokenKind::Drop,
    "E" => TokenKind::E,
    "ELSE" => TokenKind::Else,
    "EMBED" => TokenKind::Embed,
    "EMPTY" => TokenKind::Empty,
    "END" => TokenKind::End,
    "EUCLID" => TokenKind::Euclid,
    "EXACT" => TokenKind::Exact,
    "EXCLUDE" => TokenKind::Exclude,
    "EXP" => TokenKind::Exp,
    "EXP_DECAY" => TokenKind::ExpDecay,
    "EXTERIOR" => TokenKind::Exterior,
    "FALSE" => TokenKind::False,
    "FEEDBACK" => TokenKind::Feedback,
    "FIELD" => TokenKind::Field,
    "FLOAT" => TokenKind::Float,
    "FOR" => TokenKind::For,
    "FORMULA" => TokenKind::Formula,
    "FROM" => TokenKind::From,
    "FUSION" => TokenKind::Fusion,
    "GAUSS_DECAY" => TokenKind::GaussDecay,
    "GEO" => TokenKind::Geo,
    "GEO_BBOX" => TokenKind::GeoBbox,
    "GEO_DISTANCE" => TokenKind::GeoDistance,
    "GEO_POLYGON" => TokenKind::GeoPolygon,
    "GEO_RADIUS" => TokenKind::GeoRadius,
    "GROUP" => TokenKind::Group,
    "HAS_VECTOR" => TokenKind::HasVector,
    "HNSW" => TokenKind::Hnsw,
    "HNSW_EF" => TokenKind::HnswEf,
    "HYBRID" => TokenKind::Hybrid,
    "ID" => TokenKind::Id,
    "IGNORE" => TokenKind::Ignore,
    "IMAGE" => TokenKind::Image,
    "IN" => TokenKind::In,
    "INCLUDE" => TokenKind::Include,
    "INDEX" => TokenKind::Index,
    "INDEXED_ONLY" => TokenKind::IndexedOnly,
    "INDICES" => TokenKind::Indices,
    "INTEGER" => TokenKind::Integer,
    "INTERIORS" => TokenKind::Interiors,
    "INTO" => TokenKind::Into,
    "IS" => TokenKind::Is,
    "KEY" => TokenKind::Key,
    "KEYS" => TokenKind::Keys,
    "KEYWORD" => TokenKind::Keyword,
    "LAT" => TokenKind::Lat,
    "LIMIT" => TokenKind::Limit,
    "LIN_DECAY" => TokenKind::LinDecay,
    "LN" => TokenKind::Ln,
    "LOG" => TokenKind::Log,
    "LON" => TokenKind::Lon,
    "LOOKUP" => TokenKind::Lookup,
    "MAJORITY" => TokenKind::Majority,
    "MANHATTAN" => TokenKind::Manhattan,
    "MATCH" => TokenKind::Match,
    "MATCH_ANY" => TokenKind::MatchAny,
    "MAX_SELECTIVITY" => TokenKind::MaxSelectivity,
    "MIDPOINT" => TokenKind::Midpoint,
    "MMR" => TokenKind::Mmr,
    "MODEL" => TokenKind::Model,
    "MULTI" => TokenKind::Multi,
    "MULTIVECTOR" => TokenKind::Multivector,
    "NAIVE" => TokenKind::Naive,
    "NEAREST" => TokenKind::Nearest,
    "NEGATIVE" => TokenKind::Negative,
    "NESTED" => TokenKind::Nested,
    "NOT" => TokenKind::Not,
    "NULL" => TokenKind::Null,
    "OFFSET" => TokenKind::Offset,
    "ON" => TokenKind::On,
    "OPTIMIZERS" => TokenKind::Optimizers,
    "OR" => TokenKind::Or,
    "ORDER" => TokenKind::Order,
    "OVERSAMPLING" => TokenKind::Oversampling,
    "PARAMS" => TokenKind::Params,
    "PAYLOAD" => TokenKind::Payload,
    "PHRASE" => TokenKind::Phrase,
    "POINT" => TokenKind::Point,
    "POINTS" => TokenKind::Points,
    "POSITIVE" => TokenKind::Positive,
    "POW" => TokenKind::Pow,
    "PREFETCH" => TokenKind::Prefetch,
    "QUANTIZATION" => TokenKind::Quantization,
    "QUERY" => TokenKind::Query,
    "QUORUM" => TokenKind::Quorum,
    "RADIUS" => TokenKind::Radius,
    "RANDOM" => TokenKind::Random,
    "RECOMMEND" => TokenKind::Recommend,
    "RELEVANCE" => TokenKind::Relevance,
    "RERANK" => TokenKind::Rerank,
    "RESCORE" => TokenKind::Rescore,
    "RRF" => TokenKind::Rrf,
    "RRF_K" => TokenKind::RrfK,
    "RRF_WEIGHTS" => TokenKind::RrfWeights,
    "SAMPLE" => TokenKind::Sample,
    "SCALE" => TokenKind::Scale,
    "SCORE" => TokenKind::Score,
    "SCROLL" => TokenKind::Scroll,
    "SET" => TokenKind::Set,
    "SHARD" => TokenKind::Shard,
    "SHOW" => TokenKind::Show,
    "SIZE" => TokenKind::Size,
    "SPARSE" => TokenKind::Sparse,
    "SQRT" => TokenKind::Sqrt,
    "STRATEGY" => TokenKind::Strategy,
    "SUM_SCORES" => TokenKind::SumScores,
    "TARGET" => TokenKind::Target,
    "TEXT" => TokenKind::Text,
    "THEN" => TokenKind::Then,
    "THRESHOLD" => TokenKind::Threshold,
    "TIMEOUT" => TokenKind::Timeout,
    "TOP_LEFT" => TokenKind::TopLeft,
    "TRUE" => TokenKind::True,
    "TYPE" => TokenKind::Type,
    "UPDATE" => TokenKind::Update,
    "UPSERT" => TokenKind::Upsert,
    "USING" => TokenKind::Using,
    "UUID" => TokenKind::Uuid,
    "VALUES" => TokenKind::Values,
    "VALUES_COUNT" => TokenKind::ValuesCount,
    "VECTOR" => TokenKind::Vector,
    "WHEN" => TokenKind::When,
    "WHERE" => TokenKind::Where,
    "WITH" => TokenKind::With,
    "X" => TokenKind::X,
}

impl TokenKind {
    pub fn is_keyword_or_identifier(&self) -> bool {
        !matches!(
            self,
            Self::String
                | Self::Lbrace
                | Self::Rbrace
                | Self::Lbracket
                | Self::Rbracket
                | Self::Lparen
                | Self::Rparen
                | Self::Colon
                | Self::Comma
                | Self::Equals
                | Self::NotEquals
                | Self::Gt
                | Self::Gte
                | Self::Lt
                | Self::Lte
                | Self::Plus
                | Self::Minus
                | Self::Slash
                | Self::Semicolon
                | Self::Eof
        )
    }
}

impl fmt::Display for TokenKind {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str(self.as_str())
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize))]
pub struct Token<'a> {
    pub kind: TokenKind,
    pub text: &'a str,
    pub span: Span,
    #[cfg_attr(feature = "serde", serde(skip))]
    pub(crate) pos: usize,
}

impl<'a> Token<'a> {
    pub fn new(kind: TokenKind, text: &'a str, span: Span) -> Self {
        Token {
            kind,
            text,
            pos: span.start,
            span,
        }
    }

    pub fn eof(position: usize) -> Self {
        Token {
            kind: TokenKind::Eof,
            text: "",
            span: Span::point(position),
            pos: position,
        }
    }

    pub fn is_keyword_or_identifier(&self) -> bool {
        match self.kind {
            TokenKind::String
            | TokenKind::Lbrace
            | TokenKind::Rbrace
            | TokenKind::Lbracket
            | TokenKind::Rbracket
            | TokenKind::Lparen
            | TokenKind::Rparen
            | TokenKind::Colon
            | TokenKind::Comma
            | TokenKind::Equals
            | TokenKind::NotEquals
            | TokenKind::Gt
            | TokenKind::Gte
            | TokenKind::Lt
            | TokenKind::Lte
            | TokenKind::Plus
            | TokenKind::Minus
            | TokenKind::Slash
            | TokenKind::Semicolon
            | TokenKind::Eof => false,
            TokenKind::Integer | TokenKind::Float => self
                .text
                .bytes()
                .next()
                .is_some_and(|b| b.is_ascii_alphabetic()),
            _ => true,
        }
    }
}

impl<'a> fmt::Display for Token<'a> {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "{}({})", self.kind, self.text)
    }
}

pub fn lookup_keyword(s: &str) -> Option<TokenKind> {
    let bytes = s.as_bytes();
    let len = bytes.len();
    if len == 0 || len > 32 {
        return None;
    }
    let mut buf = [0u8; 32];
    for (i, b) in bytes.iter().enumerate() {
        buf[i] = b.to_ascii_uppercase();
    }
    let upper = core::str::from_utf8(&buf[..len]).ok()?;
    KEYWORDS.get(upper).copied()
}
