use std::env;
use std::error::Error;
use std::fs;
use std::path::{Path, PathBuf};

const GENERATED_HEADER: &str = "\
// @generated by qql-grammar-gen. DO NOT EDIT.
// Source: language/v1/grammar.pest
//
// Run `cargo run -p qql-grammar-gen -- generate` after changing the source.

";

struct Artifact {
    path: PathBuf,
    contents: String,
}

fn main() {
    if let Err(error) = run() {
        eprintln!("qql-grammar-gen: {error}");
        std::process::exit(1);
    }
}

fn run() -> Result<(), Box<dyn Error>> {
    let command = env::args().nth(1).unwrap_or_else(|| "check".to_owned());
    let root = workspace_root();
    let source_path = root.join("language/v1/grammar.pest");
    let source = fs::read_to_string(&source_path)?;
    let literals = grammar_literals(&source);
    let artifacts = [
        Artifact {
            path: root.join("crates/qql-core/grammar/qql.generated.pest"),
            contents: render_pest(&source),
        },
        Artifact {
            path: root.join("editors/vscode/syntaxes/qql.tmLanguage.json"),
            contents: render_textmate(&literals),
        },
        Artifact {
            path: root.join("editors/vscode/src/keywords.generated.ts"),
            contents: render_typescript(&literals),
        },
        Artifact {
            path: root.join("website/src/scripts/qql-keywords.generated.ts"),
            contents: render_typescript(&literals),
        },
        Artifact {
            path: root.join("crates/qql-core/src/keywords.generated.rs"),
            contents: render_rust_keywords(&literals),
        },
    ];

    let dead = dead_rules(&source);
    if !dead.is_empty() {
        let message = format!(
            "dead grammar rules (defined but unreachable from `script`/`single_statement`): {}",
            dead.join(", ")
        );
        if command == "check" {
            return Err(message.into());
        }
        eprintln!("qql-grammar-gen: warning: {message}");
    }

    match command.as_str() {
        "generate" => artifacts
            .iter()
            .try_for_each(|artifact| write_if_changed(&artifact.path, &artifact.contents)),
        "check" => artifacts
            .iter()
            .try_for_each(|artifact| check(&artifact.path, &artifact.contents)),
        "help" | "-h" | "--help" => {
            println!("Usage: qql-grammar-gen <generate|check>");
            Ok(())
        }
        _ => Err(format!("unknown command '{command}'; expected generate or check").into()),
    }
}

fn workspace_root() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .and_then(Path::parent)
        .expect("qql-grammar-gen must live under <workspace>/crates")
        .to_path_buf()
}

fn render_pest(source: &str) -> String {
    let normalized = source.replace("\r\n", "\n");
    let body = normalized.trim_end();
    format!("{GENERATED_HEADER}{body}\n")
}

fn grammar_literals(source: &str) -> Vec<String> {
    let bytes = source.as_bytes();
    let mut literals = Vec::new();
    let mut i = 0;
    while i < bytes.len() {
        match bytes[i] {
            b'/' if bytes.get(i + 1) == Some(&b'/') => {
                while i < bytes.len() && bytes[i] != b'\n' {
                    i += 1;
                }
            }
            b'"' => {
                // Skip a double-quoted string literal; pest supports `\"`
                // escapes inside literals, so consume backslash pairs.
                i += 1;
                while i < bytes.len() {
                    if bytes[i] == b'\\' {
                        i += 2;
                    } else if bytes[i] == b'"' {
                        i += 1;
                        break;
                    } else {
                        i += 1;
                    }
                }
            }
            b'^' if bytes.get(i + 1) == Some(&b'"') => {
                let mut end = i + 2;
                while end < bytes.len() && bytes[end] != b'"' {
                    end += 1;
                }
                let literal = &source[i + 2..end];
                // Keyword literals are ASCII words of length > 1. Single-char
                // literals (`^"a"`, `^"b"`, `^"c"`, `^"e"`, `^"E"`, `^"x"`)
                // are contextual tokens (feedback params, decay args,
                // exponents), deliberately not keyword variants.
                if literal
                    .bytes()
                    .all(|byte| byte.is_ascii_alphabetic() || byte == b'_')
                    && literal.len() > 1
                {
                    literals.push(literal.to_ascii_uppercase());
                }
                i = end + 1;
            }
            _ => i += 1,
        }
    }

    literals.sort_by_key(|literal| literal.to_ascii_uppercase());
    literals.dedup();
    literals
}

/// Extract `name = { body }` rule definitions. Bodies may span multiple lines.
fn rule_definitions(source: &str) -> Vec<(String, String)> {
    let lines: Vec<&str> = source.lines().collect();
    let mut rules = Vec::new();
    let mut i = 0;
    while i < lines.len() {
        let line = lines[i];
        let trimmed = line.trim();
        if trimmed.is_empty() || trimmed.starts_with("//") {
            i += 1;
            continue;
        }
        if let Some(eq) = first_unquoted(trimmed, '=') {
            let name = trimmed[..eq].trim();
            if is_rule_name(name) {
                let mut rest = trimmed[eq + 1..].trim_start();
                // pest rule modifiers: `_`, `@`, `$`.
                loop {
                    let before = rest;
                    for marker in ['_', '@', '$'] {
                        rest = rest.strip_prefix(marker).unwrap_or(rest).trim_start();
                    }
                    if rest == before {
                        break;
                    }
                }
                if let Some(open) = rest.find('{') {
                    let mut body = String::from(&rest[open..]);
                    let mut depth = brace_delta(&body);
                    let mut j = i + 1;
                    while depth > 0 && j < lines.len() {
                        body.push('\n');
                        body.push_str(lines[j]);
                        depth += brace_delta(lines[j]);
                        j += 1;
                    }
                    rules.push((name.to_string(), body));
                    i = j;
                    continue;
                }
            }
        }
        i += 1;
    }
    rules
}

/// Find the byte offset of `needle` in `text`, ignoring string literals.
fn first_unquoted(text: &str, needle: char) -> Option<usize> {
    let mut in_string = false;
    let mut iter = text.char_indices();
    while let Some((idx, ch)) = iter.next() {
        match ch {
            '"' => in_string = !in_string,
            c if c == needle && !in_string => return Some(idx),
            '^' => {
                // `^"..."` — skip the whole literal.
                if let Some((_, next)) = iter.next() {
                    if next == '"' {
                        for (_, c) in iter.by_ref() {
                            if c == '"' {
                                break;
                            }
                        }
                    }
                }
            }
            _ => {}
        }
    }
    None
}

fn is_rule_name(name: &str) -> bool {
    let mut chars = name.chars();
    match chars.next() {
        Some(c) if c.is_ascii_alphabetic() || c == '_' => {
            chars.all(|c| c.is_ascii_alphanumeric() || c == '_')
        }
        _ => false,
    }
}

fn brace_delta(text: &str) -> isize {
    let mut delta = 0isize;
    let mut in_string = false;
    let mut chars = text.chars().peekable();
    while let Some(ch) = chars.next() {
        match ch {
            '"' => in_string = !in_string,
            '{' if !in_string => delta += 1,
            '}' if !in_string => delta -= 1,
            '^' if chars.peek() == Some(&'"') => {
                chars.next();
                for c in chars.by_ref() {
                    if c == '"' {
                        break;
                    }
                }
            }
            _ => {}
        }
    }
    delta
}

/// Rule names referenced from a rule body (excluding string literals).
fn rule_references(body: &str, defined: &std::collections::HashSet<String>) -> Vec<String> {
    let mut refs = Vec::new();
    let mut in_string = false;
    let chars: Vec<char> = body.chars().collect();
    let mut i = 0;
    while i < chars.len() {
        match chars[i] {
            '"' => {
                in_string = !in_string;
                i += 1;
            }
            '^' if i + 1 < chars.len() && chars[i + 1] == '"' => {
                i += 2;
                while i < chars.len() && chars[i] != '"' {
                    i += 1;
                }
                i += 1;
            }
            c if !in_string && (c.is_ascii_alphabetic() || c == '_') => {
                let start = i;
                while i < chars.len() && (chars[i].is_ascii_alphanumeric() || chars[i] == '_') {
                    i += 1;
                }
                let word: String = chars[start..i].iter().collect();
                if defined.contains(&word) {
                    refs.push(word);
                }
            }
            _ => i += 1,
        }
    }
    refs
}

/// Rules defined in the grammar that are unreachable from the entry
/// productions. `WHITESPACE` and `COMMENT` are implicit pest hooks and are
/// treated as roots.
fn dead_rules(source: &str) -> Vec<String> {
    use std::collections::{HashMap, HashSet};

    let definitions = rule_definitions(source);
    let names: HashSet<String> = definitions.iter().map(|(name, _)| name.clone()).collect();
    let references: HashMap<String, Vec<String>> = definitions
        .iter()
        .map(|(name, body)| (name.clone(), rule_references(body, &names)))
        .collect();

    let mut reachable = HashSet::new();
    let mut stack = vec![
        "script".to_string(),
        "single_statement".to_string(),
        "WHITESPACE".to_string(),
        "COMMENT".to_string(),
    ];
    while let Some(name) = stack.pop() {
        if !reachable.insert(name.clone()) {
            continue;
        }
        if let Some(deps) = references.get(&name) {
            for dep in deps {
                if !reachable.contains(dep) {
                    stack.push(dep.clone());
                }
            }
        }
    }

    let mut dead: Vec<String> = names
        .into_iter()
        .filter(|name| !reachable.contains(name))
        .collect();
    dead.sort();
    dead
}

fn render_typescript(literals: &[String]) -> String {
    let constants = literals
        .iter()
        .filter(|literal| is_constant(literal))
        .map(|literal| literal.to_ascii_uppercase())
        .collect::<Vec<_>>();
    let keywords = literals
        .iter()
        .filter(|literal| !is_constant(literal))
        .map(|literal| format!("  \"{}\",", literal.to_ascii_uppercase()))
        .collect::<Vec<_>>()
        .join("\n");
    let constants = constants
        .iter()
        .map(|literal| format!("  \"{literal}\","))
        .collect::<Vec<_>>()
        .join("\n");

    format!(
        "{GENERATED_HEADER}export const QQL_KEYWORDS = [\n{keywords}\n] as const;\n\
         export const QQL_CONSTANTS = new Set([\n{constants}\n]);\n"
    )
}

/// Operators accepted by `comparison_op` in grammar.pest, in longest-first
/// alternation order. Derived here (not hard-coded in the template) so the
/// TextMate highlight cannot drift from the grammar: `<>` is not a QQL
/// operator, and the Unicode forms `≠`, `≥`, `≤` are.
const COMPARISON_OPERATORS: &[&str] = &["!=", ">=", "<=", "≠", "≥", "≤", "=", ">", "<"];

fn render_textmate(literals: &[String]) -> String {
    let constants = literals
        .iter()
        .filter(|literal| is_constant(literal))
        .cloned()
        .collect::<Vec<_>>();
    let keywords = literals
        .iter()
        .filter(|literal| !is_constant(literal))
        .cloned()
        .collect::<Vec<_>>();
    let keyword_pattern = textmate_pattern(&keywords);
    let constant_pattern = textmate_pattern(&constants);
    let comparison_operator_pattern = COMPARISON_OPERATORS.join("|");

    format!(
        r##"{{
  "name": "QQL",
  "scopeName": "source.qql",
  "fileTypes": ["qql"],
  "patterns": [
    {{ "include": "#comments" }},
    {{ "include": "#strings" }},
    {{ "include": "#parameters" }},
    {{ "include": "#numbers" }},
    {{ "include": "#constants" }},
    {{ "include": "#keywords" }},
    {{ "include": "#operators" }},
    {{ "include": "#punctuation" }},
    {{ "include": "#identifiers" }}
  ],
  "repository": {{
    "comments": {{ "patterns": [{{ "name": "comment.line.double-dash.qql", "match": "--.*$" }}] }},
    "strings": {{
      "patterns": [
        {{ "name": "string.quoted.single.qql", "begin": "'", "end": "'", "patterns": [{{ "name": "constant.character.escape.qql", "match": "''|\\\\['\\\"\\\\ntr]" }}] }},
        {{ "name": "string.quoted.double.qql", "begin": "\\\"", "end": "\\\"", "patterns": [{{ "name": "constant.character.escape.qql", "match": "\\\\['\\\"\\\\ntr]" }}] }},
        {{ "name": "string.quoted.backtick.qql", "begin": "`", "end": "`", "patterns": [{{ "name": "constant.character.escape.qql", "match": "\\\\." }}] }}
      ]
    }},
    "parameters": {{ "patterns": [
      {{ "name": "variable.parameter.named.qql", "match": "(?<![A-Za-z0-9_$'\"`\\]\\}}]):[A-Za-z_][A-Za-z0-9_]*" }},
      {{ "name": "variable.parameter.positional.qql", "match": "\\?" }}
    ] }},
    "numbers": {{ "patterns": [{{ "name": "constant.numeric.float.qql", "match": "-?\\\\d+(\\\\.\\\\d+([eE][+-]?\\\\d+)?|([eE][+-]?\\\\d+))" }}, {{ "name": "constant.numeric.integer.qql", "match": "-?\\\\d+" }}] }},
    "constants": {{ "patterns": [{{ "name": "constant.language.qql", "match": "{constant_pattern}" }}] }},
    "keywords": {{ "patterns": [{{ "name": "keyword.control.qql", "match": "{keyword_pattern}" }}] }},
    "operators": {{ "patterns": [{{ "name": "keyword.operator.comparison.qql", "match": "{comparison_operator_pattern}" }}, {{ "name": "keyword.operator.assignment.qql", "match": "=" }}, {{ "name": "keyword.operator.arithmetic.qql", "match": "[\\\\+\\\\-\\\\*\\\\/]" }}] }},
    "punctuation": {{ "patterns": [{{ "name": "punctuation.terminator.qql", "match": ";" }}, {{ "name": "punctuation.separator.qql", "match": "," }}, {{ "name": "punctuation.definition.bracket.qql", "match": "[\\\\{{\\\\}}\\\\[\\\\]]" }}, {{ "name": "punctuation.definition.paren.qql", "match": "[\\\\(\\\\)]" }}, {{ "name": "punctuation.separator.key-value.qql", "match": ":" }}] }},
    "identifiers": {{ "patterns": [{{ "name": "variable.other.readwrite.qql", "match": "\\\\$[A-Za-z0-9_]+(\\\\.[A-Za-z_][A-Za-z0-9_]*)*(\\\\[\\\\]\\\\.?)*" }}, {{ "name": "entity.name.qql", "match": "[A-Za-z_][A-Za-z0-9_]*(\\\\.[A-Za-z_][A-Za-z0-9_]*|\\\\[\\\\]\\\\.?)*" }}] }}
  }}
}}
"##
    )
}

fn is_constant(literal: &str) -> bool {
    literal.eq_ignore_ascii_case("true")
        || literal.eq_ignore_ascii_case("false")
        || literal.eq_ignore_ascii_case("null")
}

fn textmate_pattern(literals: &[String]) -> String {
    format!(r#"\\b(?i)({})\\b"#, literals.join("|"))
}

fn to_camel_case(literal: &str) -> String {
    literal
        .split('_')
        .map(|part| {
            let mut c = part.chars();
            match c.next() {
                None => String::new(),
                Some(f) => {
                    f.to_uppercase().collect::<String>() + c.as_str().to_lowercase().as_str()
                }
            }
        })
        .collect()
}

fn render_rust_keywords(literals: &[String]) -> String {
    let mut lines = Vec::new();
    for lit in literals {
        let variant = to_camel_case(lit);
        lines.push(format!("    \"{lit}\" => TokenKind::{variant},"));
    }
    let body = lines.join("\n");
    format!(
        "{GENERATED_HEADER}/// Keyword lookup table: uppercase keyword text to token kind.\npub static KEYWORDS: phf::Map<&'static str, TokenKind> = phf::phf_map! {{\n{body}\n}};\n"
    )
}

fn write_if_changed(path: &Path, contents: &str) -> Result<(), Box<dyn Error>> {
    if fs::read_to_string(path).ok().as_deref() == Some(contents) {
        println!("current: {}", path.display());
        return Ok(());
    }

    let parent = path
        .parent()
        .ok_or_else(|| format!("generated path has no parent: {}", path.display()))?;
    fs::create_dir_all(parent)?;
    let temporary = path.with_extension(format!(
        "{}.tmp",
        path.extension()
            .and_then(|ext| ext.to_str())
            .unwrap_or("generated")
    ));
    fs::write(&temporary, contents)?;
    fs::rename(temporary, path)?;
    println!("generated {}", path.display());
    Ok(())
}

fn check(path: &Path, expected: &str) -> Result<(), Box<dyn Error>> {
    match fs::read_to_string(path) {
        Ok(actual) if actual == expected => Ok(()),
        Ok(_) => Err(format!(
            "{} is stale; run `cargo run -p qql-grammar-gen -- generate`",
            path.display()
        )
        .into()),
        Err(error) if error.kind() == std::io::ErrorKind::NotFound => Err(format!(
            "{} is missing; run `cargo run -p qql-grammar-gen -- generate`",
            path.display()
        )
        .into()),
        Err(error) => Err(error.into()),
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn extracts_case_insensitive_word_literals_only() {
        let literals =
            grammar_literals("query = { ^\"QUERY\" ~ ^\"from\" ~ \"(\" ~ ^\"true\" ~ ^\"x\" }");
        assert_eq!(literals, ["FROM", "QUERY", "TRUE"]);
    }

    #[test]
    fn generated_textmate_uses_the_grammar_vocabulary() {
        let grammar =
            render_textmate(&["FROM".into(), "NULL".into(), "QUERY".into(), "true".into()]);
        assert!(grammar.contains(r#"\\b(?i)(FROM|QUERY)\\b"#));
        assert!(grammar.contains(r#"\\b(?i)(NULL|true)\\b"#));
    }

    #[test]
    fn flags_unreachable_rules_only() {
        let grammar = r#"
WHITESPACE = _{ " " }
script = { SOI ~ (statement ~ ";"?)* ~ EOI }
statement = _{ query | scroll }
query = { ^"QUERY" ~ collection }
scroll = { ^"SCROLL" ~ collection }
collection = { identifier }
identifier = { ASCII_ALPHA+ }
orphan = { ^"NEVER" }
"#;
        let dead = dead_rules(grammar);
        assert_eq!(dead, ["orphan"]);
    }

    #[test]
    fn implicit_pest_hooks_are_not_dead() {
        let grammar = r#"
WHITESPACE = _{ " " }
COMMENT = _{ "--" }
script = { SOI ~ (^"QUERY" | ^"SCROLL") ~ EOI }
"#;
        assert!(dead_rules(grammar).is_empty());
    }

    #[test]
    fn scanner_ignores_comments_and_string_bodies() {
        // `//` inside a string literal and `^"` inside a string must not be
        // treated as comment / keyword starts.
        let grammar = r#"
// comment with ^"FAKE" inside
WHITESPACE = _{ " " | "\t" }
string = @{ "\"" ~ (!"\"" ~ ANY)* ~ "\"" }
rule = { ^"REAL" ~ "//not a comment" ~ ^"ALSO_REAL" }
"#;
        assert_eq!(grammar_literals(grammar), ["ALSO_REAL", "REAL"]);
    }

    #[test]
    fn generated_textmate_operators_derive_from_comparison_op() {
        let grammar = render_textmate(&["FROM".into()]);
        // Unicode operators present, `<>` absent.
        assert!(grammar.contains("!=|>=|<=|≠|≥|≤|=|>|<"));
        assert!(!grammar.contains("<>"));
    }

    #[test]
    fn grammar_literals_match_generated_keywords_exactly() {
        // Exact bidirectional keyword check: the generated `KEYWORDS` map must
        // be exactly the grammar's keyword literal set (and vice versa), so a
        // hand-edit of either file cannot drift from the canonical grammar.
        let root = workspace_root();
        let grammar_source = fs::read_to_string(root.join("language/v1/grammar.pest")).unwrap();
        let generated =
            fs::read_to_string(root.join("crates/qql-core/src/keywords.generated.rs")).unwrap();
        let from_grammar = grammar_literals(&grammar_source);

        // Extract `"KEY" => TokenKind::Variant,` rows from the generated map.
        let mut from_map: Vec<String> = generated
            .lines()
            .filter_map(|line| {
                let line = line.trim();
                let key = line.split("=>").next()?.trim();
                key.strip_prefix('"')?.strip_suffix('"').map(str::to_owned)
            })
            .collect();
        from_map.sort();
        from_map.dedup();

        assert!(
            !from_grammar.is_empty(),
            "grammar must contain keyword literals"
        );
        assert_eq!(
            from_grammar, from_map,
            "grammar.pest keyword literals and keywords.generated.rs must match exactly"
        );
    }
}
