//! First-class collection dump → `.qql` script exporter.
//!
//! Emits:
//! 1. `CREATE COLLECTION` from typed vector schema (sizes, distances, sparse)
//! 2. `CREATE INDEX` from typed payload index specs
//! 3. Batched `UPSERT` with real `vector:` values (not re-embed stubs)
//!
//! Scroll uses cursor pagination and `with_vector: true` so every page
//! includes stored vectors. Output is streamed to disk to bound memory.

mod cursor;
mod escape;
mod indexes;
mod point;
mod quant;
mod schema;

use std::error::Error;
use std::fs::{self, File};
use std::io::{BufWriter, Write};
use std::path::Path;

use qql::executor::Executor;
use qql_plan::PlannedOperation;
use qql_plan::semantic::PlanPointId;
use qql_plan::types::{PayloadSelectorReq, ScrollRequest, VectorSelectorReq};

use cursor::{extract_scroll_page, json_to_plan_point_id};
use indexes::generate_index_statements;
use point::{point_to_upsert_object, write_upsert_batch};
use schema::generate_create_statement;

// ── Public API ──────────────────────────────────────────────────

/// Result summary of a dump run.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct DumpStats {
    pub written: usize,
    pub skipped: usize,
    pub batches: usize,
}

/// Progress details emitted after each batch during dump execution.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct DumpProgress {
    pub collection: String,
    pub written: usize,
    pub skipped: usize,
    pub batches: usize,
}

/// Dump a collection to a `.qql` script file atomically.
///
/// Output is streamed to a temporary file (`.tmp`) and renamed to `output_path`
/// on successful completion. If an error occurs, any pre-existing file at `output_path`
/// is preserved untouched, and the temporary file is removed.
pub async fn dump_collection(
    executor: &Executor,
    collection: &str,
    output_path: &str,
    batch_size: u32,
    progress: Option<&(dyn Fn(DumpProgress) + Sync)>,
) -> Result<DumpStats, Box<dyn Error>> {
    let tmp_path = format!("{}.tmp", output_path);
    let res = dump_collection_inner(executor, collection, &tmp_path, batch_size, progress).await;
    match res {
        Ok(stats) => {
            // Atomic replace when possible; fall back to copy on cross-device rename.
            if let Err(rename_err) = fs::rename(&tmp_path, output_path) {
                if let Err(copy_err) = fs::copy(&tmp_path, output_path) {
                    // Keep .tmp for recovery; surface both failures.
                    return Err(format!(
                        "failed to finalize dump at '{}': rename error: {}; copy error: {}",
                        output_path, rename_err, copy_err
                    )
                    .into());
                }
                let _ = fs::remove_file(&tmp_path);
            }
            Ok(stats)
        }
        Err(err) => {
            if Path::new(&tmp_path).exists() {
                let _ = fs::remove_file(&tmp_path);
            }
            Err(err)
        }
    }
}

async fn dump_collection_inner(
    executor: &Executor,
    collection: &str,
    output_path: &str,
    batch_size: u32,
    progress: Option<&(dyn Fn(DumpProgress) + Sync)>,
) -> Result<DumpStats, Box<dyn Error>> {
    if batch_size == 0 {
        return Err("batch_size must be >= 1".into());
    }

    let ops = executor.ops();

    let exists = ops.collection_exists(collection).await?;
    if !exists {
        return Err(format!("collection '{}' does not exist", collection).into());
    }

    let info = ops.get_collection_info(collection).await?;

    if let Some(parent) = Path::new(output_path).parent()
        && !parent.as_os_str().is_empty()
    {
        fs::create_dir_all(parent)?;
    }

    let file = File::create(output_path)?;
    let mut out = BufWriter::new(file);

    writeln!(out, "-- QQL dump for {}", collection)?;
    writeln!(out, "-- Generated by qql dump")?;
    writeln!(out)?;

    let create = generate_create_statement(collection, &info);
    writeln!(out, "{};", create)?;
    writeln!(out)?;

    let indexes = generate_index_statements(collection, &info.schema.payload_indexes);
    if !indexes.is_empty() {
        for idx in &indexes {
            writeln!(out, "{};", idx)?;
        }
        writeln!(out)?;
    }

    let mut written = 0usize;
    let mut skipped = 0usize;
    let mut batches = 0usize;
    let mut after: Option<PlanPointId> = None;

    loop {
        let op = PlannedOperation::Scroll {
            collection: collection.to_string(),
            request: ScrollRequest {
                filter: None,
                offset: after.clone(),
                limit: Some(batch_size as u64),
                with_payload: Some(PayloadSelectorReq::All(true)),
                with_vector: Some(VectorSelectorReq::All(true)),
                order_by: None,
                shard_key: None,
            },
        };

        let response = ops.execute_planned(&op).await?;
        let (points, next) = extract_scroll_page(&response);

        if points.is_empty() {
            break;
        }

        let mut records = Vec::with_capacity(points.len());
        for point in &points {
            match point_to_upsert_object(point) {
                Some(rec) => records.push(rec),
                None => skipped += 1,
            }
        }

        if !records.is_empty() {
            write_upsert_batch(&mut out, collection, &records)?;
            written += records.len();
            batches += 1;

            if let Some(cb) = progress {
                cb(DumpProgress {
                    collection: collection.to_string(),
                    written,
                    skipped,
                    batches,
                });
            }
        }

        // Prefer Qdrant's next_page_offset; fall back to last point id.
        let prev_after = after;
        after = next.or_else(|| {
            points
                .last()
                .and_then(|p| p.get("id"))
                .and_then(json_to_plan_point_id)
        });

        // Guard against a stuck cursor (same offset on a full page → infinite loop).
        if after.is_none()
            || points.len() < batch_size as usize
            || after.as_ref() == prev_after.as_ref()
        {
            break;
        }
    }

    writeln!(out)?;
    writeln!(out, "-- Written: {}", written)?;
    writeln!(out, "-- Skipped: {}", skipped)?;
    writeln!(out, "-- Batches: {}", batches)?;
    out.flush()?;

    Ok(DumpStats {
        written,
        skipped,
        batches,
    })
}

#[cfg(test)]
mod tests;
